name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -6 -H "[${{ secrets.VM_IP }}]" >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ root@[${{ secrets.VM_IP }}]:/fluffworks
