name: Deploy to VM

on:
  push:
    branches:
      - main  # ou la branche sur laquelle tu souhaites déclencher le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{ secrets.VM_IP }}" >> ~/.ssh/known_hosts

      - name: Deploy to VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          rsync -avz -e "ssh -i ~/.ssh/deploy_key" ./ user@${{ secrets.VM_IP }}:/fluffworks
