name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh-keyscan -6v -H "${{ secrets.VM_IP }}" >> ~/.ssh/known_hosts
          rsync -avz -e "ssh root@[${{ secrets.VM_IP }}]:/fluffworks"
