name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test IPv6 Connectivity
        run: |
         ping -6v -c 3 "@${{ secrets.VM_IP }}"
    
      - name: Deploy to VM
        run: |
         rsync -avz -e "ssh -6v -o StrictHostKeyChecking=no" ./ root@[${{ secrets.VM_IP }}]:/fluffworks

